services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
